### PR TITLE
Add npmjs badge to README

### LINKED ISSUE #85: Add link to npmjs
Maybe make the [link](https://www.npmjs.com/package/@metahub/karma-jasmine-jquery) to npmjs.com as the "web site" to this GitHub project?

### PR DESCRIPTION
**Pull request by ashawley**
Fixes #85.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7d7379dd81ef9135cd701410b8be53075981220e
  * Commits must be in the following format: **%{type}(?%?{scope})?: %{description}**



---
This message was auto-generated by https://gitcop.com

**Comment by pvdlg** [comment]
All the PR/issues you are opening are related to repo maintenance. If things are the way they are in my repos, this is because I made that choice, and for which I have several reason.

Feel free to open issues/PRs to fix bugs and add features, but please stop trying to force your way of maintaining a repo onto other people.

**Comment by ashawley** [comment]
It was not my intent to force how to maintain a repo on you.   I was just trying to share back some small improvements to a useful package that you've clearly spent time to publish.  Sorry that it came across that way.

Thanks for karma-jasmine-jquery,
Aaron

**Comment by pvdlg** [comment]
I usually add an npm badge when I release on multiple dist-tag to clarify which version has been released where. For this project I release everything on `@latest`, so I won't add a badge as it's redundant with the GitHub release tab.

**Pull request closed without merging**
